{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "atp") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atp
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
