# Which docker image should be used to deploy
DOCKER_TAG: ""
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
# IP of db
PG_DB_ADDR: "my-postgres-postgresql"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main"
CONTENT_SECURITY_POLICY: "*"
pg_pass: "postgrestest"
pg_user: "postgres"
MAIL_SENDER_ENABLE: "false"
ATP_SERVICE_PUBLIC: "false"
JMX_ENABLE: "false"
KAFKA_ENABLE: "false"
SERVICE_ENTITIES_MIGRATION_ENABLED: 'false'
EI_GRIDFS_ENABLED: "false"
GRIDFS_DB_ADDR: ""